- name: vars at task level
  hosts: local
  connection: local
  vars:
    course: ansible
    duration: 10h
    trainer: shiva

  tasks:
  - name: print course info.
    vars:
      course: devops
    ansible.builtin.debug:
      msg: "course is: {{course}}, duration: {{duration}}, trainer: {{trainer}}"

   