- name: vars from prompt
  hosts: local
  connection: local

  tasks:
  - name: print credentials
    ansible.builtin.debug:
      msg: "course: {{course}}, duratiion: {{duration}}, trainer: {{trainer}}"

# ansible-playbook -i inventory.ini -e ansible_user=ec2-user -e ansible_password=DevOps321 -e "COURSE=Ansible" -e "DURATION=10HRS" -e "Trainer=Sivakumar" 09-vars-args.yaml