- name: facts
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: install nginx if redhat
    ansible.builtin.dnf:
      name: nginx
      state: latest
    when: ansible_os_family == "rehat"

  - name: install nginx if debian
    ansible.builtin.apt:
      name: nginx
      state: latest
    when: ansible_os_family == "debian"  

