- name: functions or filters
  hosts: local
  connection: local
  become: yes
  vars:
    technologies: linux, ansible, devops #string
    name: "vikaS" 
    gmail: "iNFOo@gmail.com"
    ipaddress: "192.12.3.1"
    # dictionary
    tags:
     application: payment
     environment: dev
    #lists
    listtags:
    - key: environment
      value: dev
    - key: application
      value: payment

  tasks:
  - name: default variables
    ansible.builtin.debug:
      msg: "hello, {{ name | default('ramesh') }}"

    #string to list
  - name: string to list
    ansible.builtin.debug:
      msg: "technologies are: {{ technologies | split (',') }}"
  
    
  - name: map to list
    ansible.builtin.debug:
      msg: "tags are: {{ tags | dict2items }}"
    
  - name: list to map
    ansible.builtin.debug:
      msg: "tag maps: {{ listtags | items2dict }}"  

  - name: read yaml and take it into variable
    ansible.builtin.set_fact:
      student_yaml: "{{ lookup('file' , 'student.yaml') | from_yaml }}"

  - name: convert yaml into json
    ansible.builtin.debug:
       msg: "json: {{ student_yaml | to_json }}"

  - name: save json to file
    ansible.builtin.copy:
      dest: ./student-data.json
      content: "{{ student_yaml | to_nice_json }}"

  - name: convert upper case
    ansible.builtin.debug:
      msg: "{{ gmail | lower}}"

  - name: convert upper case
    ansible.builtin.debug:
      msg: "{{ name | upper}}"

  - name: ip address is valid or not
    ansible.builtin.debug:
      msg: "{{ ipaddress | ansible.utils.ipv4 }}"
    ignore_errors: true

  - name: grep root
    ansible.builtin.shell: cat /etc/passwd | grep root
    register: command_output

  - name: print the command command_output
    ansible.builtin.debug:
      msg: "{{command_output}}"    

  - name: redirect the command_output
    ansible.builtin.command: ls -ltr > /temp/output.txt
    register: redirect_output
    ignore errors: true

  - name: print the redirect output command
    ansible.builtun.debug:
      msg: "{{redirect_output}}"

  - name: redirect the command_output shell
    ansible.builtin.shell: ls -ltr > /tmp/output.txt
    register: redirect_output

  - name: print the redirect output shell
    ansible.builtin.debug:
      msg: "{{redirect_output}}"    
          
